# 开发环境

# 环境设置
[app]
use = "debug"
product = "release"

# 秘钥
[keys]
public_key = ""
private_key = ""
sig_key = ""
aes_key = ""
iv = ""

# jwt 加密方式不一样。 jwt使用特殊的私钥
[jwt]
public_key = ""
private_key = ""

# http服务
[http]
address = ""
port = 8300
read_timeout = 30
write_timeout = 30

# path 日志目录
# level 等级 trace|debug|info|warn|error|fatal|panic
[log]
path = "./logs/app.log"
level = "debug"
stdout = false
save_day = 7
timestamp_format = "2006-01-02T15:04:05.999999"

# mysql
[mysql]
debug = true
host = "localhost"
port = 3306
user = "root"
password = "123123"
database = "test"
charset = "utf8"
max_idle_conn = 10
max_open_conn = 50
max_life_time = 3600

# redis
[redis]
host = "localhost"
port = 6379
password = ""
database = 1

